# 
# Do not Edit! Generated by:
# spectacle version 0.18
# 
# >> macros
# << macros

Name:       libogg
Summary:    The Ogg bitstream file format library
Version:    1.2.0
Release:    1
Group:      System/Libraries
License:    BSD
URL:        http://www.xiph.org/
Source0:    http://downloads.xiph.org/releases/ogg/%{name}-%{version}.tar.gz
Source100:  libogg.yaml
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig


%description
Libogg is a library for manipulating Ogg bitstream file formats.
Libogg supports both making Ogg bitstreams and getting packets from
Ogg bitstreams.



%package devel
Summary:    Files needed for development using libogg
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
Libogg is a library used for manipulating Ogg bitstreams. The
libogg-devel package contains the header files and documentation
needed for development using libogg.


%package doc
Summary:    Documentation for the Ogg runtime library
Group:      Documentation
Requires:   %{name} = %{version}-%{release}

%description doc
Documentation for developing applications with libogg



%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static
make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 

# >> install post
chmod -x doc/*.html
rm -rf __installed_docs
mv $RPM_BUILD_ROOT%{_docdir}/%{name}-%{version} __installed_docs

# rename directory to match index.html
mv __installed_docs/ogg __installed_docs/libogg

# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig








%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS COPYING
%{_libdir}/libogg.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%doc CHANGES README
%dir %{_includedir}/ogg
%{_includedir}/ogg/ogg.h
%{_includedir}/ogg/os_types.h
%{_includedir}/ogg/config_types.h
%{_libdir}/libogg.so
%{_libdir}/pkgconfig/ogg.pc
%{_datadir}/aclocal/ogg.m4
# << files devel

%files doc
%defattr(-,root,root,-)
# >> files doc
%doc __installed_docs/*
# << files doc

